// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/task/infra/deviceclient (interfaces: DeviceClient)
//
// Generated by this command:
//
//	mockgen -destination=mock_device_client.go -package=task github.com/KasumiMercury/primind-central-backend/internal/task/infra/deviceclient DeviceClient
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"

	deviceclient "github.com/KasumiMercury/primind-central-backend/internal/task/infra/deviceclient"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceClient is a mock of DeviceClient interface.
type MockDeviceClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceClientMockRecorder
	isgomock struct{}
}

// MockDeviceClientMockRecorder is the mock recorder for MockDeviceClient.
type MockDeviceClientMockRecorder struct {
	mock *MockDeviceClient
}

// NewMockDeviceClient creates a new mock instance.
func NewMockDeviceClient(ctrl *gomock.Controller) *MockDeviceClient {
	mock := &MockDeviceClient{ctrl: ctrl}
	mock.recorder = &MockDeviceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceClient) EXPECT() *MockDeviceClientMockRecorder {
	return m.recorder
}

// GetUserDevices mocks base method.
func (m *MockDeviceClient) GetUserDevices(ctx context.Context, sessionToken string) ([]deviceclient.DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDevices", ctx, sessionToken)
	ret0, _ := ret[0].([]deviceclient.DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDevices indicates an expected call of GetUserDevices.
func (mr *MockDeviceClientMockRecorder) GetUserDevices(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDevices", reflect.TypeOf((*MockDeviceClient)(nil).GetUserDevices), ctx, sessionToken)
}

// GetUserDevicesWithRetry mocks base method.
func (m *MockDeviceClient) GetUserDevicesWithRetry(ctx context.Context, sessionToken string, config deviceclient.RetryConfig) ([]deviceclient.DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDevicesWithRetry", ctx, sessionToken, config)
	ret0, _ := ret[0].([]deviceclient.DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDevicesWithRetry indicates an expected call of GetUserDevicesWithRetry.
func (mr *MockDeviceClientMockRecorder) GetUserDevicesWithRetry(ctx, sessionToken, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDevicesWithRetry", reflect.TypeOf((*MockDeviceClient)(nil).GetUserDevicesWithRetry), ctx, sessionToken, config)
}
