// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -source=queue.go -destination=mock_queue.go -package=remindregister
//

// Package remindregister is a generated GoMock package.
package remindregister

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// RegisterRemind mocks base method.
func (m *MockQueue) RegisterRemind(ctx context.Context, req *CreateRemindRequest) (*RemindResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRemind", ctx, req)
	ret0, _ := ret[0].(*RemindResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterRemind indicates an expected call of RegisterRemind.
func (mr *MockQueueMockRecorder) RegisterRemind(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRemind", reflect.TypeOf((*MockQueue)(nil).RegisterRemind), ctx, req)
}
