// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/session (interfaces: TokenVerifier)
//
// Generated by this command:
//
//	mockgen -destination=mock_token_verifier.go -package=session github.com/KasumiMercury/primind-central-backend/internal/auth/app/session TokenVerifier
//

// Package session is a generated GoMock package.
package session

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenVerifier is a mock of TokenVerifier interface.
type MockTokenVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVerifierMockRecorder
	isgomock struct{}
}

// MockTokenVerifierMockRecorder is the mock recorder for MockTokenVerifier.
type MockTokenVerifierMockRecorder struct {
	mock *MockTokenVerifier
}

// NewMockTokenVerifier creates a new mock instance.
func NewMockTokenVerifier(ctrl *gomock.Controller) *MockTokenVerifier {
	mock := &MockTokenVerifier{ctrl: ctrl}
	mock.recorder = &MockTokenVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVerifier) EXPECT() *MockTokenVerifierMockRecorder {
	return m.recorder
}

// ExtractSessionID mocks base method.
func (m *MockTokenVerifier) ExtractSessionID(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSessionID", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractSessionID indicates an expected call of ExtractSessionID.
func (mr *MockTokenVerifierMockRecorder) ExtractSessionID(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSessionID", reflect.TypeOf((*MockTokenVerifier)(nil).ExtractSessionID), token)
}

// Verify mocks base method.
func (m *MockTokenVerifier) Verify(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockTokenVerifierMockRecorder) Verify(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTokenVerifier)(nil).Verify), token)
}
