// Code generated by MockGen. DO NOT EDIT.
// Source: params_repository.go
//
// Generated by this command:
//
//	mockgen -source=params_repository.go -destination=mock_params_repository.go -package=oidc
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockParamsRepository is a mock of ParamsRepository interface.
type MockParamsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParamsRepositoryMockRecorder
	isgomock struct{}
}

// MockParamsRepositoryMockRecorder is the mock recorder for MockParamsRepository.
type MockParamsRepositoryMockRecorder struct {
	mock *MockParamsRepository
}

// NewMockParamsRepository creates a new mock instance.
func NewMockParamsRepository(ctrl *gomock.Controller) *MockParamsRepository {
	mock := &MockParamsRepository{ctrl: ctrl}
	mock.recorder = &MockParamsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParamsRepository) EXPECT() *MockParamsRepositoryMockRecorder {
	return m.recorder
}

// GetParamsByState mocks base method.
func (m *MockParamsRepository) GetParamsByState(ctx context.Context, state string) (*Params, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParamsByState", ctx, state)
	ret0, _ := ret[0].(*Params)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParamsByState indicates an expected call of GetParamsByState.
func (mr *MockParamsRepositoryMockRecorder) GetParamsByState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParamsByState", reflect.TypeOf((*MockParamsRepository)(nil).GetParamsByState), ctx, state)
}

// SaveParams mocks base method.
func (m *MockParamsRepository) SaveParams(ctx context.Context, params *Params) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveParams", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveParams indicates an expected call of SaveParams.
func (mr *MockParamsRepositoryMockRecorder) SaveParams(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveParams", reflect.TypeOf((*MockParamsRepository)(nil).SaveParams), ctx, params)
}
