// Code generated by MockGen. DO NOT EDIT.
// Source: period_setting_repository.go
//
// Generated by this command:
//
//	mockgen -source=period_setting_repository.go -destination=mock_period_setting_repository.go -package=period
//

// Package period is a generated GoMock package.
package period

import (
	context "context"
	reflect "reflect"

	user "github.com/KasumiMercury/primind-central-backend/internal/task/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockPeriodSettingRepository is a mock of PeriodSettingRepository interface.
type MockPeriodSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPeriodSettingRepositoryMockRecorder
}

// MockPeriodSettingRepositoryMockRecorder is the mock recorder for MockPeriodSettingRepository.
type MockPeriodSettingRepositoryMockRecorder struct {
	mock *MockPeriodSettingRepository
}

// NewMockPeriodSettingRepository creates a new mock instance.
func NewMockPeriodSettingRepository(ctrl *gomock.Controller) *MockPeriodSettingRepository {
	mock := &MockPeriodSettingRepository{ctrl: ctrl}
	mock.recorder = &MockPeriodSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeriodSettingRepository) EXPECT() *MockPeriodSettingRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockPeriodSettingRepository) GetByUserID(ctx context.Context, userID user.ID) (*UserPeriodSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*UserPeriodSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockPeriodSettingRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockPeriodSettingRepository)(nil).GetByUserID), ctx, userID)
}

// Save mocks base method.
func (m *MockPeriodSettingRepository) Save(ctx context.Context, settings *UserPeriodSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPeriodSettingRepositoryMockRecorder) Save(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPeriodSettingRepository)(nil).Save), ctx, settings)
}
