// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/device/domain/device (interfaces: DeviceRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_device_repository.go -package=device github.com/KasumiMercury/primind-central-backend/internal/device/domain/device DeviceRepository
//

// Package device is a generated GoMock package.
package device

import (
	context "context"
	reflect "reflect"

	device "github.com/KasumiMercury/primind-central-backend/internal/device/domain/device"
	user "github.com/KasumiMercury/primind-central-backend/internal/device/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceRepository is a mock of DeviceRepository interface.
type MockDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceRepositoryMockRecorder is the mock recorder for MockDeviceRepository.
type MockDeviceRepositoryMockRecorder struct {
	mock *MockDeviceRepository
}

// NewMockDeviceRepository creates a new mock instance.
func NewMockDeviceRepository(ctrl *gomock.Controller) *MockDeviceRepository {
	mock := &MockDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepository) EXPECT() *MockDeviceRepositoryMockRecorder {
	return m.recorder
}

// DeleteDevicesByUserID mocks base method.
func (m *MockDeviceRepository) DeleteDevicesByUserID(ctx context.Context, userID user.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevicesByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevicesByUserID indicates an expected call of DeleteDevicesByUserID.
func (mr *MockDeviceRepositoryMockRecorder) DeleteDevicesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevicesByUserID", reflect.TypeOf((*MockDeviceRepository)(nil).DeleteDevicesByUserID), ctx, userID)
}

// ExistsDeviceByID mocks base method.
func (m *MockDeviceRepository) ExistsDeviceByID(ctx context.Context, id device.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsDeviceByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsDeviceByID indicates an expected call of ExistsDeviceByID.
func (mr *MockDeviceRepositoryMockRecorder) ExistsDeviceByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsDeviceByID", reflect.TypeOf((*MockDeviceRepository)(nil).ExistsDeviceByID), ctx, id)
}

// GetDeviceByID mocks base method.
func (m *MockDeviceRepository) GetDeviceByID(ctx context.Context, id device.ID) (*device.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByID", ctx, id)
	ret0, _ := ret[0].(*device.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByID indicates an expected call of GetDeviceByID.
func (mr *MockDeviceRepositoryMockRecorder) GetDeviceByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByID", reflect.TypeOf((*MockDeviceRepository)(nil).GetDeviceByID), ctx, id)
}

// GetDeviceByIDAndUserID mocks base method.
func (m *MockDeviceRepository) GetDeviceByIDAndUserID(ctx context.Context, id device.ID, userID user.ID) (*device.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByIDAndUserID", ctx, id, userID)
	ret0, _ := ret[0].(*device.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByIDAndUserID indicates an expected call of GetDeviceByIDAndUserID.
func (mr *MockDeviceRepositoryMockRecorder) GetDeviceByIDAndUserID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByIDAndUserID", reflect.TypeOf((*MockDeviceRepository)(nil).GetDeviceByIDAndUserID), ctx, id, userID)
}

// GetDeviceBySessionToken mocks base method.
func (m *MockDeviceRepository) GetDeviceBySessionToken(ctx context.Context, sessionToken string) (*device.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceBySessionToken", ctx, sessionToken)
	ret0, _ := ret[0].(*device.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceBySessionToken indicates an expected call of GetDeviceBySessionToken.
func (mr *MockDeviceRepositoryMockRecorder) GetDeviceBySessionToken(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceBySessionToken", reflect.TypeOf((*MockDeviceRepository)(nil).GetDeviceBySessionToken), ctx, sessionToken)
}

// ListDevicesByUserID mocks base method.
func (m *MockDeviceRepository) ListDevicesByUserID(ctx context.Context, userID user.ID) ([]*device.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevicesByUserID", ctx, userID)
	ret0, _ := ret[0].([]*device.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevicesByUserID indicates an expected call of ListDevicesByUserID.
func (mr *MockDeviceRepositoryMockRecorder) ListDevicesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevicesByUserID", reflect.TypeOf((*MockDeviceRepository)(nil).ListDevicesByUserID), ctx, userID)
}

// SaveDevice mocks base method.
func (m *MockDeviceRepository) SaveDevice(ctx context.Context, arg1 *device.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDevice", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDevice indicates an expected call of SaveDevice.
func (mr *MockDeviceRepositoryMockRecorder) SaveDevice(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDevice", reflect.TypeOf((*MockDeviceRepository)(nil).SaveDevice), ctx, arg1)
}

// UpdateDevice mocks base method.
func (m *MockDeviceRepository) UpdateDevice(ctx context.Context, arg1 *device.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockDeviceRepositoryMockRecorder) UpdateDevice(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockDeviceRepository)(nil).UpdateDevice), ctx, arg1)
}
