// Code generated by MockGen. DO NOT EDIT.
// Source: archive_repository.go
//
// Generated by this command:
//
//	mockgen -source=archive_repository.go -destination=mock_archive_repository.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"

	user "github.com/KasumiMercury/primind-central-backend/internal/task/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskArchiveRepository is a mock of TaskArchiveRepository interface.
type MockTaskArchiveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskArchiveRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskArchiveRepositoryMockRecorder is the mock recorder for MockTaskArchiveRepository.
type MockTaskArchiveRepositoryMockRecorder struct {
	mock *MockTaskArchiveRepository
}

// NewMockTaskArchiveRepository creates a new mock instance.
func NewMockTaskArchiveRepository(ctrl *gomock.Controller) *MockTaskArchiveRepository {
	mock := &MockTaskArchiveRepository{ctrl: ctrl}
	mock.recorder = &MockTaskArchiveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskArchiveRepository) EXPECT() *MockTaskArchiveRepositoryMockRecorder {
	return m.recorder
}

// ArchiveTask mocks base method.
func (m *MockTaskArchiveRepository) ArchiveTask(ctx context.Context, completedTask *CompletedTask, taskID ID, userID user.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveTask", ctx, completedTask, taskID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveTask indicates an expected call of ArchiveTask.
func (mr *MockTaskArchiveRepositoryMockRecorder) ArchiveTask(ctx, completedTask, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveTask", reflect.TypeOf((*MockTaskArchiveRepository)(nil).ArchiveTask), ctx, completedTask, taskID, userID)
}
