// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/task/app/task (interfaces: CreateTaskUseCase,GetTaskUseCase,ListActiveTasksUseCase,UpdateTaskUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_service_task.go -package=task github.com/KasumiMercury/primind-central-backend/internal/task/app/task CreateTaskUseCase,GetTaskUseCase,ListActiveTasksUseCase,UpdateTaskUseCase
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"

	task "github.com/KasumiMercury/primind-central-backend/internal/task/app/task"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateTaskUseCase is a mock of CreateTaskUseCase interface.
type MockCreateTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateTaskUseCaseMockRecorder is the mock recorder for MockCreateTaskUseCase.
type MockCreateTaskUseCaseMockRecorder struct {
	mock *MockCreateTaskUseCase
}

// NewMockCreateTaskUseCase creates a new mock instance.
func NewMockCreateTaskUseCase(ctrl *gomock.Controller) *MockCreateTaskUseCase {
	mock := &MockCreateTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTaskUseCase) EXPECT() *MockCreateTaskUseCaseMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockCreateTaskUseCase) CreateTask(ctx context.Context, req *task.CreateTaskRequest) (*task.CreateTaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, req)
	ret0, _ := ret[0].(*task.CreateTaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockCreateTaskUseCaseMockRecorder) CreateTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockCreateTaskUseCase)(nil).CreateTask), ctx, req)
}

// MockGetTaskUseCase is a mock of GetTaskUseCase interface.
type MockGetTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTaskUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTaskUseCaseMockRecorder is the mock recorder for MockGetTaskUseCase.
type MockGetTaskUseCaseMockRecorder struct {
	mock *MockGetTaskUseCase
}

// NewMockGetTaskUseCase creates a new mock instance.
func NewMockGetTaskUseCase(ctrl *gomock.Controller) *MockGetTaskUseCase {
	mock := &MockGetTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTaskUseCase) EXPECT() *MockGetTaskUseCaseMockRecorder {
	return m.recorder
}

// GetTask mocks base method.
func (m *MockGetTaskUseCase) GetTask(ctx context.Context, req *task.GetTaskRequest) (*task.GetTaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, req)
	ret0, _ := ret[0].(*task.GetTaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockGetTaskUseCaseMockRecorder) GetTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockGetTaskUseCase)(nil).GetTask), ctx, req)
}

// MockListActiveTasksUseCase is a mock of ListActiveTasksUseCase interface.
type MockListActiveTasksUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListActiveTasksUseCaseMockRecorder
	isgomock struct{}
}

// MockListActiveTasksUseCaseMockRecorder is the mock recorder for MockListActiveTasksUseCase.
type MockListActiveTasksUseCaseMockRecorder struct {
	mock *MockListActiveTasksUseCase
}

// NewMockListActiveTasksUseCase creates a new mock instance.
func NewMockListActiveTasksUseCase(ctrl *gomock.Controller) *MockListActiveTasksUseCase {
	mock := &MockListActiveTasksUseCase{ctrl: ctrl}
	mock.recorder = &MockListActiveTasksUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListActiveTasksUseCase) EXPECT() *MockListActiveTasksUseCaseMockRecorder {
	return m.recorder
}

// ListActiveTasks mocks base method.
func (m *MockListActiveTasksUseCase) ListActiveTasks(ctx context.Context, req *task.ListActiveTasksRequest) (*task.ListActiveTasksResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveTasks", ctx, req)
	ret0, _ := ret[0].(*task.ListActiveTasksResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveTasks indicates an expected call of ListActiveTasks.
func (mr *MockListActiveTasksUseCaseMockRecorder) ListActiveTasks(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveTasks", reflect.TypeOf((*MockListActiveTasksUseCase)(nil).ListActiveTasks), ctx, req)
}

// MockUpdateTaskUseCase is a mock of UpdateTaskUseCase interface.
type MockUpdateTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateTaskUseCaseMockRecorder is the mock recorder for MockUpdateTaskUseCase.
type MockUpdateTaskUseCaseMockRecorder struct {
	mock *MockUpdateTaskUseCase
}

// NewMockUpdateTaskUseCase creates a new mock instance.
func NewMockUpdateTaskUseCase(ctrl *gomock.Controller) *MockUpdateTaskUseCase {
	mock := &MockUpdateTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskUseCase) EXPECT() *MockUpdateTaskUseCaseMockRecorder {
	return m.recorder
}

// UpdateTask mocks base method.
func (m *MockUpdateTaskUseCase) UpdateTask(ctx context.Context, req *task.UpdateTaskRequest) (*task.UpdateTaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, req)
	ret0, _ := ret[0].(*task.UpdateTaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockUpdateTaskUseCaseMockRecorder) UpdateTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockUpdateTaskUseCase)(nil).UpdateTask), ctx, req)
}
