// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc (interfaces: UserWithOIDCIdentityRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_user_with_identity_repository.go -package=oidc github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc UserWithOIDCIdentityRepository
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	oidcidentity "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidcidentity"
	user "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserWithOIDCIdentityRepository is a mock of UserWithOIDCIdentityRepository interface.
type MockUserWithOIDCIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserWithOIDCIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockUserWithOIDCIdentityRepositoryMockRecorder is the mock recorder for MockUserWithOIDCIdentityRepository.
type MockUserWithOIDCIdentityRepositoryMockRecorder struct {
	mock *MockUserWithOIDCIdentityRepository
}

// NewMockUserWithOIDCIdentityRepository creates a new mock instance.
func NewMockUserWithOIDCIdentityRepository(ctrl *gomock.Controller) *MockUserWithOIDCIdentityRepository {
	mock := &MockUserWithOIDCIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockUserWithOIDCIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWithOIDCIdentityRepository) EXPECT() *MockUserWithOIDCIdentityRepositoryMockRecorder {
	return m.recorder
}

// SaveUserWithOIDCIdentity mocks base method.
func (m *MockUserWithOIDCIdentityRepository) SaveUserWithOIDCIdentity(ctx context.Context, arg1 *user.User, identity *oidcidentity.OIDCIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserWithOIDCIdentity", ctx, arg1, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserWithOIDCIdentity indicates an expected call of SaveUserWithOIDCIdentity.
func (mr *MockUserWithOIDCIdentityRepositoryMockRecorder) SaveUserWithOIDCIdentity(ctx, arg1, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserWithOIDCIdentity", reflect.TypeOf((*MockUserWithOIDCIdentityRepository)(nil).SaveUserWithOIDCIdentity), ctx, arg1, identity)
}
