// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc (interfaces: SessionTokenGenerator)
//
// Generated by this command:
//
//	mockgen -destination=mock_session_token_generator.go -package=oidc github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc SessionTokenGenerator
//

// Package oidc is a generated GoMock package.
package oidc

import (
	reflect "reflect"

	session "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/session"
	user "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionTokenGenerator is a mock of SessionTokenGenerator interface.
type MockSessionTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockSessionTokenGeneratorMockRecorder is the mock recorder for MockSessionTokenGenerator.
type MockSessionTokenGeneratorMockRecorder struct {
	mock *MockSessionTokenGenerator
}

// NewMockSessionTokenGenerator creates a new mock instance.
func NewMockSessionTokenGenerator(ctrl *gomock.Controller) *MockSessionTokenGenerator {
	mock := &MockSessionTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockSessionTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionTokenGenerator) EXPECT() *MockSessionTokenGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSessionTokenGenerator) Generate(arg0 *session.Session, arg1 *user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockSessionTokenGeneratorMockRecorder) Generate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSessionTokenGenerator)(nil).Generate), arg0, arg1)
}
