// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc (interfaces: OIDCProvider,OIDCProviderWithLogin)
//
// Generated by this command:
//
//	mockgen -destination=mock_oidc_provider.go -package=oidc . OIDCProvider,OIDCProviderWithLogin
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	oidc "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCProvider is a mock of OIDCProvider interface.
type MockOIDCProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCProviderMockRecorder
	isgomock struct{}
}

// MockOIDCProviderMockRecorder is the mock recorder for MockOIDCProvider.
type MockOIDCProviderMockRecorder struct {
	mock *MockOIDCProvider
}

// NewMockOIDCProvider creates a new mock instance.
func NewMockOIDCProvider(ctrl *gomock.Controller) *MockOIDCProvider {
	mock := &MockOIDCProvider{ctrl: ctrl}
	mock.recorder = &MockOIDCProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCProvider) EXPECT() *MockOIDCProviderMockRecorder {
	return m.recorder
}

// BuildAuthorizationURL mocks base method.
func (m *MockOIDCProvider) BuildAuthorizationURL(state, nonce, codeChallenge string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAuthorizationURL", state, nonce, codeChallenge)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildAuthorizationURL indicates an expected call of BuildAuthorizationURL.
func (mr *MockOIDCProviderMockRecorder) BuildAuthorizationURL(state, nonce, codeChallenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAuthorizationURL", reflect.TypeOf((*MockOIDCProvider)(nil).BuildAuthorizationURL), state, nonce, codeChallenge)
}

// ClientID mocks base method.
func (m *MockOIDCProvider) ClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientID indicates an expected call of ClientID.
func (mr *MockOIDCProviderMockRecorder) ClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientID", reflect.TypeOf((*MockOIDCProvider)(nil).ClientID))
}

// ProviderID mocks base method.
func (m *MockOIDCProvider) ProviderID() oidc.ProviderID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderID")
	ret0, _ := ret[0].(oidc.ProviderID)
	return ret0
}

// ProviderID indicates an expected call of ProviderID.
func (mr *MockOIDCProviderMockRecorder) ProviderID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderID", reflect.TypeOf((*MockOIDCProvider)(nil).ProviderID))
}

// RedirectURI mocks base method.
func (m *MockOIDCProvider) RedirectURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// RedirectURI indicates an expected call of RedirectURI.
func (mr *MockOIDCProviderMockRecorder) RedirectURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectURI", reflect.TypeOf((*MockOIDCProvider)(nil).RedirectURI))
}

// Scopes mocks base method.
func (m *MockOIDCProvider) Scopes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scopes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Scopes indicates an expected call of Scopes.
func (mr *MockOIDCProviderMockRecorder) Scopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scopes", reflect.TypeOf((*MockOIDCProvider)(nil).Scopes))
}

// MockOIDCProviderWithLogin is a mock of OIDCProviderWithLogin interface.
type MockOIDCProviderWithLogin struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCProviderWithLoginMockRecorder
	isgomock struct{}
}

// MockOIDCProviderWithLoginMockRecorder is the mock recorder for MockOIDCProviderWithLogin.
type MockOIDCProviderWithLoginMockRecorder struct {
	mock *MockOIDCProviderWithLogin
}

// NewMockOIDCProviderWithLogin creates a new mock instance.
func NewMockOIDCProviderWithLogin(ctrl *gomock.Controller) *MockOIDCProviderWithLogin {
	mock := &MockOIDCProviderWithLogin{ctrl: ctrl}
	mock.recorder = &MockOIDCProviderWithLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCProviderWithLogin) EXPECT() *MockOIDCProviderWithLoginMockRecorder {
	return m.recorder
}

// BuildAuthorizationURL mocks base method.
func (m *MockOIDCProviderWithLogin) BuildAuthorizationURL(state, nonce, codeChallenge string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAuthorizationURL", state, nonce, codeChallenge)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildAuthorizationURL indicates an expected call of BuildAuthorizationURL.
func (mr *MockOIDCProviderWithLoginMockRecorder) BuildAuthorizationURL(state, nonce, codeChallenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAuthorizationURL", reflect.TypeOf((*MockOIDCProviderWithLogin)(nil).BuildAuthorizationURL), state, nonce, codeChallenge)
}

// ClientID mocks base method.
func (m *MockOIDCProviderWithLogin) ClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientID indicates an expected call of ClientID.
func (mr *MockOIDCProviderWithLoginMockRecorder) ClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientID", reflect.TypeOf((*MockOIDCProviderWithLogin)(nil).ClientID))
}

// ExchangeToken mocks base method.
func (m *MockOIDCProviderWithLogin) ExchangeToken(ctx context.Context, code, codeVerifier, nonce string) (*IDToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeToken", ctx, code, codeVerifier, nonce)
	ret0, _ := ret[0].(*IDToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeToken indicates an expected call of ExchangeToken.
func (mr *MockOIDCProviderWithLoginMockRecorder) ExchangeToken(ctx, code, codeVerifier, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeToken", reflect.TypeOf((*MockOIDCProviderWithLogin)(nil).ExchangeToken), ctx, code, codeVerifier, nonce)
}

// ProviderID mocks base method.
func (m *MockOIDCProviderWithLogin) ProviderID() oidc.ProviderID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderID")
	ret0, _ := ret[0].(oidc.ProviderID)
	return ret0
}

// ProviderID indicates an expected call of ProviderID.
func (mr *MockOIDCProviderWithLoginMockRecorder) ProviderID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderID", reflect.TypeOf((*MockOIDCProviderWithLogin)(nil).ProviderID))
}

// RedirectURI mocks base method.
func (m *MockOIDCProviderWithLogin) RedirectURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// RedirectURI indicates an expected call of RedirectURI.
func (mr *MockOIDCProviderWithLoginMockRecorder) RedirectURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectURI", reflect.TypeOf((*MockOIDCProviderWithLogin)(nil).RedirectURI))
}

// Scopes mocks base method.
func (m *MockOIDCProviderWithLogin) Scopes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scopes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Scopes indicates an expected call of Scopes.
func (mr *MockOIDCProviderWithLoginMockRecorder) Scopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scopes", reflect.TypeOf((*MockOIDCProviderWithLogin)(nil).Scopes))
}
