// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidcidentity (interfaces: OIDCIdentityRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_oidc_identity_repository.go -package=oidc github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidcidentity OIDCIdentityRepository
//

// Package oidc is a generated GoMock package.
package oidc

import (
	context "context"
	reflect "reflect"

	oidc "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidc"
	oidcidentity "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidcidentity"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCIdentityRepository is a mock of OIDCIdentityRepository interface.
type MockOIDCIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockOIDCIdentityRepositoryMockRecorder is the mock recorder for MockOIDCIdentityRepository.
type MockOIDCIdentityRepositoryMockRecorder struct {
	mock *MockOIDCIdentityRepository
}

// NewMockOIDCIdentityRepository creates a new mock instance.
func NewMockOIDCIdentityRepository(ctrl *gomock.Controller) *MockOIDCIdentityRepository {
	mock := &MockOIDCIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockOIDCIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCIdentityRepository) EXPECT() *MockOIDCIdentityRepositoryMockRecorder {
	return m.recorder
}

// GetOIDCIdentityByProviderSubject mocks base method.
func (m *MockOIDCIdentityRepository) GetOIDCIdentityByProviderSubject(ctx context.Context, provider oidc.ProviderID, subject string) (*oidcidentity.OIDCIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOIDCIdentityByProviderSubject", ctx, provider, subject)
	ret0, _ := ret[0].(*oidcidentity.OIDCIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOIDCIdentityByProviderSubject indicates an expected call of GetOIDCIdentityByProviderSubject.
func (mr *MockOIDCIdentityRepositoryMockRecorder) GetOIDCIdentityByProviderSubject(ctx, provider, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOIDCIdentityByProviderSubject", reflect.TypeOf((*MockOIDCIdentityRepository)(nil).GetOIDCIdentityByProviderSubject), ctx, provider, subject)
}

// SaveOIDCIdentity mocks base method.
func (m *MockOIDCIdentityRepository) SaveOIDCIdentity(ctx context.Context, identity *oidcidentity.OIDCIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOIDCIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOIDCIdentity indicates an expected call of SaveOIDCIdentity.
func (mr *MockOIDCIdentityRepositoryMockRecorder) SaveOIDCIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOIDCIdentity", reflect.TypeOf((*MockOIDCIdentityRepository)(nil).SaveOIDCIdentity), ctx, identity)
}
