// Code generated by MockGen. DO NOT EDIT.
// Source: taskqueue.go
//
// Generated by this command:
//
//	mockgen -source=taskqueue.go -destination=mock_taskqueue.go -package=taskqueue
//

// Package taskqueue is a generated GoMock package.
package taskqueue

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemindQueue is a mock of RemindQueue interface.
type MockRemindQueue struct {
	ctrl     *gomock.Controller
	recorder *MockRemindQueueMockRecorder
	isgomock struct{}
}

// MockRemindQueueMockRecorder is the mock recorder for MockRemindQueue.
type MockRemindQueueMockRecorder struct {
	mock *MockRemindQueue
}

// NewMockRemindQueue creates a new mock instance.
func NewMockRemindQueue(ctrl *gomock.Controller) *MockRemindQueue {
	mock := &MockRemindQueue{ctrl: ctrl}
	mock.recorder = &MockRemindQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemindQueue) EXPECT() *MockRemindQueueMockRecorder {
	return m.recorder
}

// RegisterRemind mocks base method.
func (m *MockRemindQueue) RegisterRemind(ctx context.Context, req *CreateRemindRequest) (*RemindResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRemind", ctx, req)
	ret0, _ := ret[0].(*RemindResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterRemind indicates an expected call of RegisterRemind.
func (mr *MockRemindQueueMockRecorder) RegisterRemind(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRemind", reflect.TypeOf((*MockRemindQueue)(nil).RegisterRemind), ctx, req)
}
