// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc (interfaces: OIDCParamsGenerator,OIDCLoginUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_service_oidc.go -package=auth github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc OIDCParamsGenerator,OIDCLoginUseCase
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	oidc "github.com/KasumiMercury/primind-central-backend/internal/auth/app/oidc"
	oidc0 "github.com/KasumiMercury/primind-central-backend/internal/auth/domain/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCParamsGenerator is a mock of OIDCParamsGenerator interface.
type MockOIDCParamsGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCParamsGeneratorMockRecorder
	isgomock struct{}
}

// MockOIDCParamsGeneratorMockRecorder is the mock recorder for MockOIDCParamsGenerator.
type MockOIDCParamsGeneratorMockRecorder struct {
	mock *MockOIDCParamsGenerator
}

// NewMockOIDCParamsGenerator creates a new mock instance.
func NewMockOIDCParamsGenerator(ctrl *gomock.Controller) *MockOIDCParamsGenerator {
	mock := &MockOIDCParamsGenerator{ctrl: ctrl}
	mock.recorder = &MockOIDCParamsGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCParamsGenerator) EXPECT() *MockOIDCParamsGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockOIDCParamsGenerator) Generate(ctx context.Context, provider oidc0.ProviderID) (*oidc.ParamsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, provider)
	ret0, _ := ret[0].(*oidc.ParamsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockOIDCParamsGeneratorMockRecorder) Generate(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockOIDCParamsGenerator)(nil).Generate), ctx, provider)
}

// MockOIDCLoginUseCase is a mock of OIDCLoginUseCase interface.
type MockOIDCLoginUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCLoginUseCaseMockRecorder
	isgomock struct{}
}

// MockOIDCLoginUseCaseMockRecorder is the mock recorder for MockOIDCLoginUseCase.
type MockOIDCLoginUseCaseMockRecorder struct {
	mock *MockOIDCLoginUseCase
}

// NewMockOIDCLoginUseCase creates a new mock instance.
func NewMockOIDCLoginUseCase(ctrl *gomock.Controller) *MockOIDCLoginUseCase {
	mock := &MockOIDCLoginUseCase{ctrl: ctrl}
	mock.recorder = &MockOIDCLoginUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCLoginUseCase) EXPECT() *MockOIDCLoginUseCaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockOIDCLoginUseCase) Login(ctx context.Context, req *oidc.LoginRequest) (*oidc.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*oidc.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockOIDCLoginUseCaseMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockOIDCLoginUseCase)(nil).Login), ctx, req)
}
