// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/session (interfaces: ValidateSessionUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_service_session.go -package=auth github.com/KasumiMercury/primind-central-backend/internal/auth/app/session ValidateSessionUseCase
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	session "github.com/KasumiMercury/primind-central-backend/internal/auth/app/session"
	gomock "go.uber.org/mock/gomock"
)

// MockValidateSessionUseCase is a mock of ValidateSessionUseCase interface.
type MockValidateSessionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockValidateSessionUseCaseMockRecorder
	isgomock struct{}
}

// MockValidateSessionUseCaseMockRecorder is the mock recorder for MockValidateSessionUseCase.
type MockValidateSessionUseCaseMockRecorder struct {
	mock *MockValidateSessionUseCase
}

// NewMockValidateSessionUseCase creates a new mock instance.
func NewMockValidateSessionUseCase(ctrl *gomock.Controller) *MockValidateSessionUseCase {
	mock := &MockValidateSessionUseCase{ctrl: ctrl}
	mock.recorder = &MockValidateSessionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateSessionUseCase) EXPECT() *MockValidateSessionUseCaseMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidateSessionUseCase) Validate(ctx context.Context, req *session.ValidateSessionRequest) (*session.ValidateSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, req)
	ret0, _ := ret[0].(*session.ValidateSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockValidateSessionUseCaseMockRecorder) Validate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidateSessionUseCase)(nil).Validate), ctx, req)
}
