// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KasumiMercury/primind-central-backend/internal/auth/app/logout (interfaces: LogoutUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_service_logout.go -package=auth github.com/KasumiMercury/primind-central-backend/internal/auth/app/logout LogoutUseCase
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	logout "github.com/KasumiMercury/primind-central-backend/internal/auth/app/logout"
	gomock "go.uber.org/mock/gomock"
)

// MockLogoutUseCase is a mock of LogoutUseCase interface.
type MockLogoutUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutUseCaseMockRecorder
	isgomock struct{}
}

// MockLogoutUseCaseMockRecorder is the mock recorder for MockLogoutUseCase.
type MockLogoutUseCaseMockRecorder struct {
	mock *MockLogoutUseCase
}

// NewMockLogoutUseCase creates a new mock instance.
func NewMockLogoutUseCase(ctrl *gomock.Controller) *MockLogoutUseCase {
	mock := &MockLogoutUseCase{ctrl: ctrl}
	mock.recorder = &MockLogoutUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutUseCase) EXPECT() *MockLogoutUseCaseMockRecorder {
	return m.recorder
}

// Logout mocks base method.
func (m *MockLogoutUseCase) Logout(ctx context.Context, req *logout.LogoutRequest) (*logout.LogoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, req)
	ret0, _ := ret[0].(*logout.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockLogoutUseCaseMockRecorder) Logout(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockLogoutUseCase)(nil).Logout), ctx, req)
}
